# Generated by Django 2.2.8 on 2019-12-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tutle',
            new_name='title',
        ),
    ]
